### ISSUE TITLE
微信跳转的模块是不是失效了

### ISSUE THREAD

**Issue by chengkongyiban** [allstreaming/webpage#1]
好像失效了？日志有mitm，但是还是拦截了，之前还能用的

**Comment by kurtn2005** [comment]
现在淘宝链接都能直接打开了，这个跳转也没什么用了。

**Comment by chengkongyiban** [comment]
确实，还有就是，没有失效。类似t.me这种链接是可以直接打开的，ghs的网站不行，我之前一直试的p站。所以误解了😂😂😂
